/** Declaration file generated by dts-gen */

declare namespace hex2dec {
	export function decToHex(decStr: string, opts: { prefix?: boolean }): string;

	export function hexToDec(hexStr: string): string;
}
